# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Love Nails Algonquin
description: Love Nails Algonquin - Manicure, Pedicure Nail Salon
url: "https://lovenails-algonquin.com/"
image: /assets/svg/logo-header.svg
twitter: 
plugins:
  - jekyll-sitemap